from typing import TypedDict, Any, Iterable, TypeVar, Sequence


class NimPyException(Exception): ...

"""
################################################################################################################
Memory
################################################################################################################
"""
class _Process(TypedDict):
    name: str
    pid: int
    debug: bool
    handle: int

class _Module(TypedDict):
    name: str
    base: int
    end: int
    size: int

class _Page(TypedDict):
    start: int
    end: int
    size: int


def enum_processes() -> Iterable[_Process]: ...
def pid_exists(pid: int) -> bool: ...
def process_exists(processName: str) -> bool: ...
def get_process_id(processName: str) -> int: ...
def get_process_name(pid: int) -> str: ...
def open_process(process: str | int, debug: bool = False) -> _Process: ...
def get_process_path(process: _Process) -> str: ...
def close_process(process: _Process) -> str: ...
def enum_modules(process: _Process) -> Iterable[_Module]: ...
def module_exists(process: _Process, moduleName: str) -> bool: ...
def get_module(process: _Process, moduleName: str) -> _Module: ...
def is_64_bit(process: _Process) -> bool: ...
def process_running(process: _Process) -> bool: ...
def get_os_error() -> tuple[int, str]: ...
def get_proc_address(moduleName: str, functionName: str) -> int: ...
def create_remote_thread(process: _Process, startAddress: int, param: int) -> bool: ...
def inject_library(process: _Process, dllPath: str) -> bool: ...
def inject_shellcode(process: _Process, shellcode: str, params: int = 0) -> bool: ...
def enum_memory_regions(process: _Process, module: _Module) -> None: ...

def aob_scan_module(process: _Process, moduleName: str, pattern: str, relative: bool = False, single: bool = True, algorithm: int = 0) -> Iterable[int]: ...
def aob_scan_range(process: _Process, pattern: str, rangeStart: int, rangeEnd: int, relative: bool = False, single: bool = True, algorithm: int = 0) -> Iterable[int]: ...
def aob_scan_bytes(pattern: str, byteBuffer: bytes, single: bool = True, algorithm: int = 0) -> Iterable[int]: ...
def pointer_chain_32(process: _Process, base: int, offsets: Iterable[int]) -> int: ...
def pointer_chain_64(process: _Process, base: int, offsets: Iterable[int]) -> int: ...

def page_protection(process: _Process, address: int, newProtection: int) -> int: ...
def allocate_memory(process: _Process, size: int, protection: int = 0) -> int: ...
def free_memory(process: _Process, address: int) -> bool: ...

__CTYPE_T = TypeVar('__CTYPE_T')

def r(process: _Process, address: int, type: str, size: int = 1) -> Any: ...
def r_string(process: _Process, address: int, size: int = 30) -> str: ...
def bytes_to_string(process: _Process, address: int, size: int) -> str: ...
def r_int(process: _Process, address: int) -> int: ...
def r_ints(process: _Process, address: int, size: int) -> Iterable[int]: ...
def r_int8(process: _Process, address: int) -> int: ...
def r_ints8(process: _Process, address: int, size: int) -> Iterable[int]: ...
def r_int16(process: _Process, address: int) -> int: ...
def r_ints16(process: _Process, address: int, size: int) -> Iterable[int]: ...
def r_uint(process: _Process, address: int) -> int: ...
def r_uints(process: _Process, address: int, size: int) -> Iterable[int]: ...
def r_uint16(process: _Process, address: int) -> int: ...
def r_uints16(process: _Process, address: int, size: int) -> Iterable[int]: ...
def r_uint64(process: _Process, address: int) -> int: ...
def r_uints64(process: _Process, address: int, size: int) -> Iterable[int]: ...
def r_int64(process: _Process, address: int) -> int: ...
def r_ints64(process: _Process, address: int, size: int) -> Iterable[int]: ...
def r_float(process: _Process, address: int) -> float: ...
def r_floats(process: _Process, address: int, size: int) -> Iterable[float]: ...
def r_float64(process: _Process, address: int) -> float: ...
def r_floats64(process: _Process, address: int, size: int) -> Iterable[float]: ...
def r_byte(process: _Process, address: int) -> bytes: ...
def r_bytes(process: _Process, address: int, size: int) -> Iterable[bytes]: ...
def r_vec2(process: _Process, address: int) ->_Vector2: ...
def r_vec3(process: _Process, address: int) ->_Vector3: ...
def r_bool(process: _Process, address: int) -> bool: ...
def r_ctype(process: _Process, address: int, ctype: type[__CTYPE_T]): __CTYPE_T

def w(process: _Process, address: int, data: Any, type: str) -> None: ...
def w_string(process: _Process, address: int, data: str) -> None: ...
def w_int(process: _Process, address: int, data: int) -> None: ...
def w_ints(process: _Process, address: int, data: Iterable[int]) -> None: ...
def w_int8(process: _Process, address: int, data: int) -> None: ...
def w_ints8(process: _Process, address: int, data: Iterable[int]) -> None: ...
def w_int16(process: _Process, address: int, data: int) -> None: ...
def w_ints16(process: _Process, address: int, data: Iterable[int]) -> None: ...
def w_int64(process: _Process, address: int, data: int) -> None: ...
def w_ints64(process: _Process, address: int, data: Iterable[int]) -> None: ...
def w_uint(process: _Process, address: int, data: int) -> None: ...
def w_uints(process: _Process, address: int, data: Iterable[int]) -> None: ...
def w_uint16(process: _Process, address: int, data: int) -> None: ...
def w_uints16(process: _Process, address: int, data: Iterable[int]) -> None: ...
def w_uint64(process: _Process, address: int, data: int) -> None: ...
def w_uints64(process: _Process, address: int, data: Iterable[int]) -> None: ...
def w_float(process: _Process, address: int, data: float) -> None: ...
def w_floats(process: _Process, address: int, data: Iterable[float]) -> None: ...
def w_float64(process: _Process, address: int, data: float) -> None: ...
def w_floats64(process: _Process, address: int, data: Iterable[float]) -> None: ...
def w_byte(process: _Process, address: int, data: bytes) -> None: ...
def w_bytes(process: _Process, address: int, data: Iterable[bytes]) -> None: ...
def w_vec2(process: _Process, address: int, data: _Vector2) -> None: ...
def w_vec3(process: _Process, address: int, data: _Vector3) -> None: ...
def w_bool(process: _Process, address: int, data: bool) -> None: ...
def w_ctype(process: _Process, address: int, data: __CTYPE_T) -> None: ...


"""
################################################################################################################
Overlay
################################################################################################################
"""
def overlay_init(target: str = "Full", fps: int = 0, title: str = "PyMeow", logLevel: int = 5, exitKey: int = -1, trackTarget: bool = False) -> None: ...
def overlay_loop() -> bool: ...
def overlay_close() -> None: ...
def toggle_mouse() -> None: ...
def get_fps() -> int: ...
def get_screen_height() -> int: ...
def get_screen_width() -> int: ...
def set_window_position(x: int, y: int) -> None: ...
def get_window_position() -> _Vector2: ...
def set_fps(fps: int) -> None: ...
def set_window_size(width, height: int) -> None: ...
def set_window_icon(filePath: str) -> None: ...
def set_window_title(title: str) -> None: ...
def set_window_monitor(monitor: int) -> None: ...
def set_log_level(level: int) -> None: ...
def set_window_flag(flag: int) -> None: ...
def get_window_handle() -> int: ...


"""
################################################################################################################
Shapes / Drawing
################################################################################################################
"""
class _Rectangle(TypedDict):
    x: float
    y: float
    width: float
    height: float

class _Texture(TypedDict):
    id: int
    width: int
    height: int
    mipmap: int
    format: int

def begin_drawing() -> None: ...
def end_drawing() -> None: ...
def draw_fps(posX, posY: float) -> None: ...
def draw_text(text: str, posX: float, posY: float, fontSize: float, color: _Color) -> None: ...
def draw_pixel(posX: float, posY: float, color: _Color) -> None: ...
def draw_line(startPosX: float, startPosY: float, endPosX: float, endPosY: float, color: _Color, thick: float = 1.0) -> None: ...
def draw_circle(centerX: float, centerY: float, radius: float, color: _Color) -> None: ...
def draw_circle_lines(centerX: float, centerY: float, radius: float, color: _Color) -> None: ...
def draw_circle_sector(centerX: float, centerY: float, radius: float, startAngle: float, endAngle: float, segments: int, color: _Color) -> None: ...
def draw_circle_sector_lines(centerX: float, centerY: float, radius: float, startAngle: float, endAngle: float, segments: int, color: _Color) -> None: ...
def draw_ring(centerX: float, centerY: float, segments: float, innerRadius: float, outerRadius: float, startAngle: float, endAngle: float, color: _Color) -> None: ...
def draw_ring_lines(centerX: float, centerY: float, segments: float, innerRadius: float, outerRadius: float, startAngle: float, endAngle: float, color: _Color) -> None: ...
def draw_ellipse(centerX: float, centerY: float, radiusH: float, radiusV: float, color: _Color) -> None: ...
def draw_ellipse_lines(centerX: float, centerY: float, radiusH: float, radiusV: float, color: _Color) -> None: ...
def draw_rectangle(posX: float, posY: float, width: float, height: float, color: _Color) -> _Rectangle: ...
def draw_rectangle_lines(posX: float, posY: float, width: float, height: float, color: _Color, lineThick: float = 1.0) -> _Rectangle: ...
def draw_rectangle_rounded(posX: float, posY: float, width: float, height: float, roundness: float, segments: int, color: _Color) -> _Rectangle: ...
def draw_rectangle_rounded_lines(posX: float, posY: float, width: float, height: float, roundness: float, segments: int, color: _Color, lineThick: float = 1.0) -> _Rectangle: ...
def draw_triangle(pos1X: float, pos1Y: float, pos2X: float, pos2Y: float, pos3X: float, pos3Y: float, color: _Color) -> None: ...
def draw_triangle_lines(pos1X: float, pos1Y: float, pos2X: float, pos2Y: float, pos3X: float, pos3Y: float, color: _Color) -> None: ...
def draw_poly(posX: float, posY: float, sides: int, radius: float, rotation: float, color: _Color) -> None: ...
def draw_poly_lines(posX: float, posY: float, sides: int, radius: float, rotation: float, lineThick: float, color: _Color) -> None: ...
def load_texture(fileName: str) -> _Texture: ...
def load_texture_bytes(fileType: str, data: bytes) -> _Texture: ...
def draw_texture(texture: _Texture, posX: float, posY: float, tint: _Color, rotation: float, scale: float) -> None: ...
def unload_texture(texture: _Texture) -> None: ...
def load_font(fileName: str, fontId: int) -> None: ...
def draw_font(fontId: int, text: str, posX: float, posY: float, fontSize: float, spacing: float, tint: _Color) -> None: ...


"""
################################################################################################################
Graphical User Interface (GUI)
################################################################################################################
"""
def gui_window_box(posX: float, posY: float, width: float, height: float, title: str) -> bool: ...
def gui_group_box(posX: float, posY: float, width: float, height: float, text: str) -> None: ...
def gui_line(posX: float, posY: float, width: float, height: float, text: str) -> None: ...
def gui_panel(posX: float, posY: float, width: float, height: float) -> None: ...
def gui_label(posX: float, posY: float, width: float, height: float, text: str) -> None: ...
def gui_button(posX: float, posY: float, width: float, height: float, text: str) -> bool: ...
def gui_label_button(posX: float, posY: float, width: float, height: float, text: str) -> bool: ...
def gui_check_box(posX: float, posY: float, width: float, height: float, text: str, checked: bool) -> bool: ...
def gui_combo_box(posX: float, posY: float, width: float, height: float, text: str, active: int) -> int: ...
def gui_dropdown_box(posX: float, posY: float, width: float, height: float, text: str, id: int, active: int = 0) -> int: ...
def gui_text_box(posX: float, posY: float, width: float, height: float, text: str, id: int) -> str: ...
def gui_progress_bar(posX: float, posY: float, width: float, height: float, textLeft: str, textRight: str, value: float, minValue: float, maxValue: float) -> float: ...
def gui_status_bar(posX: float, posY: float, width: float, height: float, text: str) -> None: ...
def gui_message_box(posX: float, posY: float, width: float, height: float, title: str, message: str, buttons: str) -> int: ...
def gui_color_picker(posX: float, posY: float, width: float, height: float, id: int) -> _Color: ...
def gui_color_bar_alpha(posX: float, posY: float, width: float, height: float, alpha: float) -> float: ...
def gui_color_bar_hue(posX: float, posY: float, width: float, height: float, value: float) -> float: ...
def gui_scroll_bar(posX: float, posY: float, width: float, height: float, value: int, minValue: int, maxValue: int) -> int: ...
def gui_spinner(posX: float, posY: float, width: float, height: float, text: str, value: int, minValue: int, maxValue: int, id: int) -> int: ...
def gui_slider(posX: float, posY: float, width: float, height: float, textLeft: str, textRight: str, value: float, minValue: float, maxValue: float) -> float: ...
def gui_slider_bar(posX: float, posY: float, width: float, height: float, textLeft: str, textRight: str, value: float, minValue: float, maxValue: float) -> None: ...
def gui_load_style(fileName: str) -> None: ...
def gui_fade(alpha: float) -> None: ...
def gui_set_state(state: int) -> None: ...


"""
################################################################################################################
Vector
################################################################################################################
"""
class _Vector2(TypedDict):
    x: float
    y: float

class _Vector3(TypedDict):
    x: float
    y: float
    z: float
def vec2(x: float = 0, y: float = 0) -> _Vector2: ...
def vec2_add(v1: _Vector2, v2: _Vector2) -> _Vector2: ...
def vec2_add_value(v: _Vector2, value: float) -> _Vector2: ...
def vec2_subtract(v1: _Vector2, v2: _Vector2) -> _Vector2: ...
def vec2_subtract_value(v: _Vector2, value: float) -> _Vector2: ...
def vec2_multiply(v1: _Vector2, v2: _Vector2) -> _Vector2: ...
def vec2_multiply_value(v: _Vector2, value: float) -> _Vector2: ...
def vec2_divide(v1: _Vector2, v2: _Vector2) -> _Vector2: ...
def vec2_length(v: _Vector2) -> float: ...
def vec2_length_sqr(v: _Vector2) -> float: ...
def vec2_distance(v1: _Vector2, v2: _Vector2) -> float: ...
def vec2_closest(v: _Vector2, vectorList: Iterable[_Vector2]) -> _Vector2: ...
def vec3(x: float = 0, y: float = 0, z: float = 0) -> _Vector3: ...
def vec3_add(v1: _Vector3, v2: _Vector3) -> _Vector3: ...
def vec3_add_value(v: _Vector3, value: float) -> _Vector3: ...
def vec3_subtract(v1: _Vector3, v2: _Vector3) -> _Vector3: ...
def vec3_subtract_value(v: _Vector3, value: float) -> _Vector3: ...
def vec3_multiply(v1: _Vector3, v2: _Vector3) -> _Vector3: ...
def vec3_multiply_value(v: _Vector3, value: float) -> _Vector3: ...
def vec3_divide(v1: _Vector3, v2: _Vector3) -> _Vector3: ...
def vec3_length(v: _Vector3) -> float: ...
def vec3_length_sqr(v: _Vector3) -> float: ...
def vec3_distance(v: _Vector3) -> float: ...
def vec3_closest(v: _Vector3, vectorList: Iterable[_Vector3]) -> _Vector3: ...


"""
################################################################################################################
Pixel Scanning
################################################################################################################
"""
class _Pixel(TypedDict):
  x: int
  y: int
  color: _Color

def pixel_enum_region(x: float, y: float, width: float, height: float) -> Iterable[_Pixel]: ...
def pixel_enum_screen() -> Iterable[_Pixel]: ...
def pixel_at_mouse() -> _Pixel: ...
def pixel_save_to_file(x: float, y: float, width: float, height: float, fileName: str) -> None: ...
def pixel_search_colors(x: float, y: float, width: float, height: float, colors: Iterable[_Color], similarity: float) -> Iterable[_Pixel]: ...


"""
################################################################################################################
Sound
################################################################################################################
"""
def sound_init() -> None: ...
def sound_deinit() -> None: ...
def load_sound(fileName: str) -> int: ...
def unload_sound(soundId: int) -> None: ...
def play_sound(soundId: int) -> None: ...
def pause_sound(soundId: int) -> None: ...
def resume_sound(soundId: int) -> None: ...
def stop_sound(soundId: int) -> None: ...
def set_sound_volume(soundId: int, volume: int) -> None: ...
def is_sound_playing(soundId: int) -> None: ...
def play_multisound(soundId: int) -> None: ...
def stop_multisound() -> None: ...


"""
################################################################################################################
Misc / Utilities
################################################################################################################
"""
class _Color(TypedDict):
    r: int
    g: int
    b: int
    a: int

def system_name() -> str: ...
def get_display_resolution() -> tuple[int, int]: ...
def get_window_info(name: str) -> tuple[int, int, int, int]: ...
def get_window_title(processId: int) -> str: ...
def get_monitor_refresh_rate(monitor: int = 0) -> int: ...
def get_monitor_count() -> int: ...
def get_monitor_name(monitor: int = 0) -> str: ...
def new_color(r: int, g: int, b: int, a: int) -> _Color: ...
def new_color_hex(hexValue: int) -> _Color: ...
def new_color_float(r: float, g: float, b: float, a: float) -> _Color: ...
def get_color(colorName: str) -> _Color: ...
def all_colors() -> dict[str, _Color]: ...
def compare_color_pct(color1, color2: _Color) -> float: ...
def fade_color(color: _Color, alpha: float) -> _Color: ...
def world_to_screen(matrix: Sequence[float], pos: _Vector3, algo: int = 0) -> _Vector2: ...
def world_to_screen_noexc(matrix: Sequence[float], pos: _Vector3, algo: int = 0) -> tuple[bool, _Vector2]: ...
def key_pressed(key: int) -> bool: ...
def press_key(key: int) -> None: ...
def mouse_pressed(button: str = "left") -> bool: ...
def mouse_move(x: int, y: int, relative: bool = False) -> None: ...
def mouse_down(button: str = "left") -> None: ...
def mouse_up(button: str = "left") -> None: ...
def mouse_click(button: str = "left") -> None: ...
def mouse_position() -> tuple[float, float]: ...
def measure_text(text: str, fontSize: int) -> int: ...
def measure_font(fontId: int, text: str, fontSize: float, spacing: float) -> _Vector2: ...
def run_time() -> float: ...
def check_collision_point_rec(pointX: float, pointY: float, rec: _Rectangle) -> bool: ...
def check_collision_recs(rec1: _Rectangle, rec2: _Rectangle) -> bool: ...
def check_collision_circle_rec(posX: float, posY: float, radius: float, rec: _Rectangle) -> bool: ...
def check_collision_lines(startPos1X: float, endPos1X: float, startPos1Y: float, endPos1Y: float, startPos2X: float, startPos2Y: float, endPos2X: float, endPos2Y: float) -> _Vector2: ...
def check_collision_circles(pos1X: float, pos1Y: float, radius1: float, pos2X: float, pos2Y: float, radius2: float) -> bool: ...
def take_screenshot(fileName: str) -> None: ...